### ISSUE TITLE
Trying to make 04F3:3057 work

### ISSUE THREAD

**Issue by FliiFe** [iafilatov/libfprint#12]
I have an `ELAN1300:00  04F3:3057` touchpad with included fingerprint sensor. The thing is, I'm not even sure the fingerprint sensor should be listed separately as its own input device, but it's currently not (in `/proc/bus/input/devices` only the touchpad is listed).

Then I'd like to see if this driver can work out of the box for this fingerprint sensor (I don't know any C at all, unfortunately)

How could I do that ? (tell the driver the device to use, as currently it does show No device detected)

**Comment by iafilatov** [comment]
So far all Elan fp sensors recognized by this driver have come up as separate devices (i.e. in lsusb), even integrated in touchpad. So normally I'd expect it to show. Unless it's some kind of new device that's sooo integrated it needs just one driver. If you want try attaching this driver, copy the line at https://github.com/iafilatov/libfprint/blob/elan/libfprint/drivers/elan.h#L158 and set `.product = 0x3057`. Then compile and try it out like in readme. But I wouldn't expect much. It could well be using a completely different protocol.

**Comment by iafilatov** [comment]
There's now a how-to [here](https://github.com/iafilatov/libfprint#unrecognized-devices).

**Comment by Man-Jain** [comment]
Hey Can you confirm if this worked for you ? @FliiFe

**Comment by tjbcg** [comment]
It has not, I have yet to get this sensor to work @Man-Jain

**Comment by Man-Jain** [comment]
Oh! Thanks

**Comment by Leatherface75** [comment]
Same problem here and it doesn't even show in lsusb

> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 13d3:3526 IMC Networks 
Bus 001 Device 003: ID 13d3:5a07 IMC Networks 
Bus 001 Device 002: ID 046d:c01e Logitech, Inc. MX518 Optical Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

> [    5.706767] i2c_hid i2c-ELAN1300:00: i2c-ELAN1300:00 supply vdd not found, using dummy regulator
[    5.706807] i2c_hid i2c-ELAN1300:00: i2c-ELAN1300:00 supply vddl not found, using dummy regulator
[    7.495469] input: ELAN1300:00 04F3:3057 Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-5/i2c-ELAN1300:00/0018:04F3:3057.0001/input/input18
[    7.495760] input: ELAN1300:00 04F3:3057 Touchpad as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-5/i2c-ELAN1300:00/0018:04F3:3057.0001/input/input19
[    7.504904] hid-generic 0018:04F3:3057.0001: input,hidraw0: I2C HID v1.00 Mouse [ELAN1300:00 04F3:3057] on i2c-ELAN1300:00
[    7.713953] input: ELAN1300:00 04F3:3057 Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-5/i2c-ELAN1300:00/0018:04F3:3057.0001/input/input20
[    7.714154] input: ELAN1300:00 04F3:3057 Touchpad as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-5/i2c-ELAN1300:00/0018:04F3:3057.0001/input/input21
[    7.714338] hid-multitouch 0018:04F3:3057.0001: input,hidraw0: I2C HID v1.00 Mouse [ELAN1300:00 04F3:3057] on i2c-ELAN1300:00

**Comment by mincrmatt12** [comment]
I have a prototype driver for these sensors on my fork of libfprint at [mincrmatt12/libfprint](https://github.com/mincrmatt12/libfprint/tree/mincrmatt12/elan-spi), although because these sensors talk via an amalgamation of SPI and vendor-defined HID commands it requires a bit of system setup to get working (see the README [here](https://github.com/mincrmatt12/elan-spi-fingerprint)). It works for the one system I've tested it with, but YMMV. It also has the same problem that all the sensors here do, which is that it's way too small for the normal libfprint matching algorithm, so you have to swipe your finger across the sensor (which is a bit annoying given that it's embedded in the touchpad)
