### ISSUE TITLE
Native dependency "udev" not found, but libgudev & libgudev-devel installed

### ISSUE THREAD

**Issue by moore-bryan** [iafilatov/libfprint#14]
Any thoughts?
[meson-log.txt](https://github.com/iafilatov/libfprint/files/2137606/meson-log.txt)

**Comment by iafilatov** [comment]
libudev-devel?

**Comment by moore-bryan** [comment]
I'm on Solus and that's the "dev" name...

**Comment by iafilatov** [comment]
Without the "g". libudev and libgudev are different projects. You need headers for libudev.

**Comment by moore-bryan** [comment]
Solus doesn't have libudev, only libgudev; well, it does have python3-pyudev, but I already have that installed and still no love.

Guess I'll need to go compiling!

**Comment by moore-bryan** [comment]
It looks as though installing systemd-devel on Solus fixes this issue... thanks for being my sounding board!

**Comment by iafilatov** [comment]
Here's what I found https://solus-project.com/forums/viewtopic.php?t=10141

**Comment by qsantos** [comment]
Same issue on Debian, had to install `systemd-dev`
