### ISSUE TITLE
Fingerprint not reliable

### ISSUE THREAD

**Issue by frlacf** [iafilatov/libfprint#20]
Hi, 
first of all, thank you for your great work.

Concerning the problem, I find the reader very unreliable, I did the fprint-enroll about 20 times and still can't get a single match with fprint-verify. I think the problem come from the fingerprint reader itself: it is not made for a ''Swipe'' finger identification. The size of the reader (about 1cm by 1cm) makes it more appropriate for ''single scan'' authentication.

I might be wrong though.

have a nice day and continue your great work !

Francis

**Comment by iafilatov** [comment]
Hi Francis, this is a [known problem](https://github.com/iafilatov/libfprint#common-problems) and unfortunately not much can be done at this point.
