### ISSUE TITLE
Will it ever be possible to change to touch input rather than swipe?

### ISSUE THREAD

**Issue by blackICE19240** [iafilatov/libfprint#24]
I've just been having a lot of trouble with swipe in linux compared to touch in windows so I had to ask. I very much appreciate the work either way.

**Comment by iafilatov** [comment]
That's how I did it from the start but it just didn't work. There's currently no way to make touch work any better with Elan than swipe.
https://github.com/iafilatov/libfprint#common-problems
https://github.com/iafilatov/libfprint/issues/21#issuecomment-416720525
