### ISSUE TITLE
Asus UX461UN | Unrecognized device

### ISSUE THREAD

**Issue by andreo-code** [iafilatov/libfprint#25]
Hey. I successfully installed your program on ubuntu 18.10. Unfortunately, my device is unrecognized on my new Asus UX461UN. I also realized that the lsusb | command grep -i elan does not show my fingerprint reader device info. Here is the thread about it https://ubuntuforums.org/showthread.php?t=2388793 . Unfortunately, I did not find any more information. I can not find any driver. What can you advise me in this situation? Is there a chance that the driver will appear? Best Regards

**Comment by iafilatov** [comment]
Hi Andrzej, it looks like your fingerprint sensor is connected to SPI bus. libfprint only supports USB devices at the moment so unfortunately this driver won't work for you. Sorry..

**Comment by andreo-code** [comment]
Ok, it's hard. Thanks for your response.
